cmake_minimum_required(VERSION 4.0)
project(LW1)

set(CMAKE_CXX_STANDARD 23)

add_executable(LW1 main.cpp
        Task1.cpp
        Headers/Task1.h
        Headers/BaseTask.h
        Task2.cpp
        Headers/Task2.h
        Task3.cpp
        Headers/Task3.h
        Task4.cpp
        Headers/Task4.h
        Task5.cpp
        Headers/Task5.h
        Task6.cpp
        Headers/Task6.h
        Task7.cpp
        Headers/Task7.h
        TaskMenu.cpp
        Headers/TaskMenu.h)
